name: flightbook-website

on:
  pull_request:
    branches:
      - main
    paths:
      - 'flightbook-website/**'
      - '.github/workflows/flightbook-website.yml'
  push:
    branches:
      - main
    paths:
      - 'flightbook-website/**'
      - '.github/workflows/flightbook-website.yml'

defaults:
  run:
    working-directory: flightbook-website

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 22
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: flightbook-website/package-lock.json
      - run: npm ci
      - run: npm run build
      # - run: npm test

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: flightbook-website/package-lock.json
      - run: npm ci
      - run: npm run check
